services:
    nginx:
        container_name: my-nginx-sservice
        image: my-nginx-service
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./mynginx.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        ports:
             - "7093:80"
        networks:
             - core

networks:
  core:
    external: true