services:
    catalog:
        container_name: microservice1
        image: microservice-service_1
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        ports:
             - "7074:80"
        networks:
             - es_net
        expose:
             - "80"

networks:
  es_net:
    external: true